serranoltexx: Fix typo and build
Cause:

   ERROR: couldn't find ro.product.device in build.prop

Change-Id: I6f5b823d32a1a66339269704a3dd109681aabc42